#---- GENERAL SETTINGS

CACHE_DIR: './tmp/'

#---- DATASET URLS

URLS:
    posenet: 'https://zenodo.org/record/5803076/files/posenet.zip'
    openpose: 'https://zenodo.org/record/5803076/files/openpose.zip'
   
#---- DATASET CONSTANTS
DATASET:
    T: 30
    C: 3
    
    posenet:
        K: 17
        k: 13
        k_axp: 13
        center_1: 5
        center_2: 6
        module_keypoint: 0
        head: [0, 1, 2, 3, 4]
        right_foot: [15]
        left_foot: [16]
        prune: []
            
    openpose:
        K: 25
        k: 15
        k_axp: 13
        center_1: 1
        center_2: 1
        module_keypoint: 8
        head: [0, 15, 16, 17, 18]
        right_foot: [11, 22, 23, 24]
        left_foot: [14, 19, 20, 21]
        prune: [1,8]
        
    labels: {
        "standing":0,
        "check-watch":1,
        "cross-arms":2,
        "scratch-head":3,
        "sit-down":4,
        "get-up":5,
        "turn":6, 
        "walk":7, 
        "wave1":8,
        "box":9,
        "kick":10,
        "point":11, 
        "pick-up":12,
        "bend":13,
        "hands-clap":14,
        "wave2":15,
        "jog":16,
        "jump":17,
        "pjump":18,
        "run":19
        }